url: https://schnuffi-page.github.io

# Site settings
title: Schnuffi's page
email: schnuffi.in.love@gmail.com
description: "Liebe ist... für immer wir zwei!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ffa316 #fed136
  secondary: fec503  
  secondary-dark: 6b2247 #43152c #333
  secondary-bright: 6a8bde #5ff0b2

# Team names, titles and social links
people:
- name: Schnuffi
  pic: 1
  position: Schlummerbär

- name: #
  pic: 2
  position: #


- name: Schatzi
  pic: 3
  position: Kuschelbär

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty